### ISSUE TITLE
Problem running the 2D batch analysis

### ISSUE THREAD

**Issue by OJ10596** [AhsenChaudhry/Mitochondria-Analyzer#8]
Hi,

First of all, the Mitochondria Analyzer plugin is amazing, and the update which does most of the pre- and post-processing of the images is very convenient! Thanks for that!

Now to the issue : I was trying to run the 2D Batch Analysis commands on a folder of images which I want to analyze for the mitochondrial architecture.  These are single channel images which I have saved as 8-bit. When I click the "2D Batch Commands" option, it asks for a folder. After selection, I set my determined block-size and C-values and select a "per-cell analysis." I click "ok" but there is no response/output after that.

The code seems to run but there is no output. There are no saved images or new folders created with the analysis. Further, there is no table with any results. If there was any error, I expected some response from ImageJ saying that there is an error. But there is nothing- no error popup or anything. The code runs to completion and that's it, no result!

Could you please help me out here? Is there something I should do which might solve this or which has previously worked with someone else? Any advices?

Please let me know! Thanks!

P.S: All the other thresholding and analysis commands work fine.

**Comment by AhsenChaudhry** [comment]
Hello, thank you for notifying me of this issue. I wanted to confirm what format the files are in? The batch command is currently set up to look only for .tif files in a folder, so if the images are in a different format, this may be the cause for your issue. If you require the images to be in a different file format, an easy fix is to go into the code for the Batch2D command, and change the value of the variable 'suffix' (on Line 12) to whatever file format you want. Hopefully this helps!

I have also updated the Batch commands to throw an error now if it does not find any images to analyze, making it more clear what the issue is.
